<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Save_OSFillParent</name>
   <tag></tag>
   <elementGuidId>7efac174-123b-4fc0-866e-ecb12cc7ed7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-Column2']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.OSFillParent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>762c57a2-49c5-412b-97ba-1f092e6388c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent</value>
      <webElementGuid>52c86c83-77f4-4a0f-a751-92398d706c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/SandboxReactive_AT/img/SandboxReactive_AT.Request.png?Gtb2BThKLk5eroubAkcjnw</value>
      <webElementGuid>bd70f49f-0ffb-4269-99ed-e0e0d70a0bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-Column2&quot;)/img[@class=&quot;OSFillParent&quot;]</value>
      <webElementGuid>bf295abf-f319-42d2-8383-c771eb0fddfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-Column2']/img</value>
      <webElementGuid>37bbf7fe-9a32-405f-b388-7b60be9ca074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>d26fe791-73a5-4de7-9526-1f2064e698b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/SandboxReactive_AT/img/SandboxReactive_AT.Request.png?Gtb2BThKLk5eroubAkcjnw']</value>
      <webElementGuid>31c2758c-4485-461c-a95d-f639d0cbf650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
