<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Checkbox1</name>
   <tag></tag>
   <elementGuidId>70e304d3-39b1-45a2-b2bb-f20ae4a6b5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a98e2ad-1f00-4e87-8f68-7567ba6d05bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2ac4e53a-433c-4e71-aa78-5998bf84452f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d5c1225a-18b2-41ba-ba71-1576c455662b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remember me the password</value>
      <webElementGuid>9e927475-cd2f-4790-9f5e-b525399359c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Checkbox1</value>
      <webElementGuid>da581479-abe3-4d8d-bc33-80e335cbbc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Checkbox1&quot;)</value>
      <webElementGuid>7ed425f1-8d56-48fe-9e19-18b883118018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Checkbox1']</value>
      <webElementGuid>42c5124e-8579-45d6-bd2e-fb14adb5fc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-Content']/span/input</value>
      <webElementGuid>fc5628e0-c3d3-4404-9b08-2687cd575571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/span/input</value>
      <webElementGuid>6f5125b1-8790-4243-a243-ebd08ff6af94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Checkbox1']</value>
      <webElementGuid>632d7828-ee72-4ed6-a4de-6262e27bc9f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
